apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: triggerbinding-master-github
  namespace: nordmart-build
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: repoName
      value: $(body.repository.name)
    - name: prnumberBranch
      value: master
    - name: prnumber
      value: NA
    - name: namespace
      value: nordmart-build
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
    - name: image_registry_url
      value: "docker.io/stakater/$(body.repository.name)"
