kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stakater-tekton-builder
  namespace: nordmart-build
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineresources
    verbs:
      - get
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stakater-tekton-builder
  namespace: nordmart-build
subjects:
  - kind: ServiceAccount
    name: stakater-tekton-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stakater-tekton-builder