apiVersion: v1
kind: ServiceAccount
metadata:
  name: stakater-tekton-builder
  namespace: nordmart-build
secrets:
  - name: git-auth
  - name: registry-auth
  - name: docker-auth
imagePullSecrets:
- name: docker-auth