apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-image-puller
  name: kubernetes-image-puller-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubernetes-image-puller-operator
  template:
    metadata:
      labels:
        name: kubernetes-image-puller-operator
    spec:
      serviceAccountName: kubernetes-image-puller-operator
      containers:
        - name: kubernetes-image-puller-operator
          # Replace this with the built image name
          image: quay.io/eclipse/kubernetes-image-puller-operator:0.0.1
          command:
          - kubernetes-image-puller-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubernetes-image-puller-operator"
