kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: commit-status-tracker
  namespace: nordmart-build
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - update
  - get
  - list
  - patch
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - commit-status-tracker
  verbs:
  - "update"
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: commit-status-tracker
  namespace: nordmart-build
subjects:
- kind: ServiceAccount
  name: commit-status-tracker
roleRef:
  kind: Role
  name: commit-status-tracker
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commit-status-tracker
  namespace: nordmart-build