apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-eventlistener
  namespace: nordmart-build
spec:
  serviceAccountName: stakater-tekton-builder
  triggers:
    - name: pullrequest-merge-trigger
      interceptors:
        - cel:
            filter: >-
              (header.match('X-GitHub-Event', 'pull_request') &&
              body.action == 'closed' )
      bindings:
      - ref: triggerbinding-merge-pr
      template:
        name: docker-pr-merge-triggertemplate
    
    - name: pullrequest-trigger
      interceptors:
        - cel:
            filter: >-
              (header.match('X-GitHub-Event', 'pull_request') &&
              body.action == 'opened' || body.action == 'synchronize')
      bindings:
      - ref: triggerbinding-pr-github
      template:
        name: docker-triggertemplate-github
    - name: push-trigger
      interceptors:
        - cel:
            filter: >-
              (header.match('X-GitHub-Event', 'push') &&
              body.ref == 'refs/heads/master')
      bindings:
      - ref: triggerbinding-master-github
      template:
        name: docker-triggertemplate-github
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    category: route
    router: default
  name: github-webhook
  namespace: nordmart-build
  annotations:
    # haproxy.router.openshift.io/ip_whitelist: 34.74.90.64/28
spec:
  port:
    targetPort: http-listener
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: el-github-eventlistener
    weight: 100
  wildcardPolicy: None
